### ISSUE TITLE
Support parsing Entity from yaml/json files

### ISSUE THREAD

**Issue by prune998** [datolabs-io/go-backstage#51]
Hi,
first, thanks for supporting this project.

Our backstage setup use a `catalog.yaml` file stores in our git repos (gitlab). 
I'm working on some tooling to generate/maintain this yaml file.

One of my needs is to get the file from Git, parse it as a Go struct, update some fields then open a PR with the change.

I tried using the `Entity` struct to parse the yaml, but I then need to have the specific fields of a `Component` or a `System` (= I need to  cast the entity to the right type so I can directly access the right fields.
 
It feels to me it's lacking some functions to get access to each entity's specific fields, as mostly all public functions are intended to use a client that connects to the Backstage API.

Maybe I'm missing something as I'm not the best Go dev :) 
Any advice or help would be greatly appreciated. If you can show me the right direction I can PR the needed changes ?

Thanks !

**Comment by prune998** [comment]
Here's part of my code, but I just don't understand how to access the specific fields of an `Entity` that is a `Component`.
Also, Marshalling it back to Yaml does not work:

```go
	// decode yaml and store objects
	d := yaml.NewDecoder(bytes.NewBufferString(string(content)))
	for {
		// decode the spec here
		spec := new(backstage.Entity)
		err := d.Decode(&spec)
		// check it was parsed
		if spec == nil {
			continue
		}

		// break the loop in case of EOF
		if errors.Is(err, io.EOF) {
			break
		}

		if spec.Kind == backstage.KindComponent {

                   // try to access the Entity specific fields
                   ....

                 specAsYaml, err := yaml.Marshal(spec)
					if err != nil {
						return err
					}
					fmt.Println(string(specAsYaml))
                  ....
                  }
...
```

**Comment by tdabasinskas** [comment]
Hi,

Haven't tested, but I think it should be something like this:

```go
buf, _ := ioutil.ReadFile(r.Path)
c := &backstage.Entity{}
_ = yaml.Unmarshal(buf, c)
if c.Kind == backstage.KindComponent {
    e := &backstage.ComponentEntityV1alpha1
    _ = yaml.Unmarshal(buf, e)
}
```

There's no error handling and you should handle multiple YAML documents in the file (as per your previous example), but I think it should like that.
